server:
  port: 9090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.15.222:3306/easydai?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0
mybatis:
  type-aliases-package: com.qf.j1902.pojo
  mapper-locations: classpath:mapping/*.xml

